"""Automatic test-case harness: turns recorded ledger activity into pytest
regression fixtures, so policy changes get caught by CI instead of only being
noticed in production.

Cases come from real traffic recorded in the ledger, not from synthesizing
inputs for arbitrary predicates — a policy with no recorded activity yet
produces no cases until it has actually fired at least once.
"""

from __future__ import annotations

from typing import Literal

from tollgate.ledger.event import LedgerEvent

Framework = Literal["pytest"]


def fixtures_from_events(events: list[LedgerEvent], framework: Framework = "pytest") -> str:
    """Render every distinct `(policy, tool, decision)` combination observed in
    `events` as a pytest test function asserting `tollgate.replay()` reproduces
    it against a `policies` fixture supplied by the caller's test suite."""
    if framework != "pytest":
        raise ValueError(f"unsupported test harness framework: {framework!r}")

    seen: dict[str, LedgerEvent] = {}
    for event in events:
        if event.policy is None:
            continue
        seen[f"{event.policy}::{event.tool}::{event.decision}"] = event

    lines = [
        "# Auto-generated by tollgate.testing.harness.fixtures_from_events().",
        "# Each test replays a recorded ledger event and asserts the decision",
        "# is reproduced by the policies currently in effect (a 'policies' fixture",
        "# must be provided by the test suite).",
        "from tollgate.ledger.ledger import replay",
        "",
    ]
    for key, event in seen.items():
        fn_name = "test_" + "".join(c if c.isalnum() else "_" for c in key).lower()
        lines.append(f"def {fn_name}(policies):")
        lines.append(f"    result = replay({event.event_id!r}, policies=policies)")
        lines.append(f"    assert result.context.tool_name == {event.tool!r}")
        lines.append("    assert not result.changed, result.new_results")
        lines.append("")
    return "\n".join(lines)
