"""Automatic test-case harness: turns recorded ledger activity into pytest
regression fixtures, so policy changes get caught by CI instead of only being
noticed in production.

Cases come from real traffic recorded in the ledger, not from synthesizing
inputs for arbitrary predicates — a policy with no recorded activity yet
produces no cases until it has actually fired at least once.
"""

from __future__ import annotations

from typing import Literal

from chokepoint.errors import ConfigurationError
from chokepoint.ledger.event import LedgerEvent
from chokepoint.redaction import contains_placeholder

Framework = Literal["pytest"]


def fixtures_from_events(events: list[LedgerEvent], framework: Framework = "pytest") -> str:
    """Render every distinct `(policy, tool, decision)` combination observed in
    `events` as a pytest test function asserting `chokepoint.replay()` reproduces
    it against a `policies` fixture supplied by the caller's test suite.

    Events whose arguments were redacted are emitted as skipped tests rather
    than dropped: replaying one feeds placeholders to the predicates, so it
    could never pass, but silently omitting it would misrepresent how much of
    the recorded traffic is actually covered.
    """
    if framework != "pytest":
        raise ConfigurationError(f"unsupported test harness framework: {framework!r}")

    seen: dict[str, LedgerEvent] = {}
    for event in events:
        if event.policy is None:
            continue
        seen[f"{event.policy}::{event.tool}::{event.decision}"] = event

    any_redacted = any(contains_placeholder(e.args) for e in seen.values())
    lines = [
        "# Auto-generated by chokepoint.testing.harness.fixtures_from_events().",
        "# Each test replays a recorded ledger event and asserts the decision",
        "# is reproduced by the policies currently in effect (a 'policies' fixture",
        "# must be provided by the test suite).",
    ]
    if any_redacted:
        lines += [
            "#",
            "# Some events were recorded with redacted arguments and are skipped:",
            "# replaying them would evaluate policies against placeholders. To cover",
            "# those calls, narrow redaction for the tools you need to replay — see",
            "# chokepoint.configure_redaction().",
            "import pytest",
        ]
    lines += ["from chokepoint.ledger.ledger import replay", ""]

    for key, event in seen.items():
        fn_name = "test_" + "".join(c if c.isalnum() else "_" for c in key).lower()
        if contains_placeholder(event.args):
            lines.append('@pytest.mark.skip(reason="arguments were redacted; replay is not comparable")')
        lines.append(f"def {fn_name}(policies):")
        lines.append(f"    result = replay({event.event_id!r}, policies=policies)")
        lines.append(f"    assert result.context.tool_name == {event.tool!r}")
        lines.append("    assert not result.changed, result.new_results")
        lines.append("")
    return "\n".join(lines)
